# store.swagger.yaml

/{storeId}/review:
  post:
    summary: Uploads a file.
    consumes:
      - multipart/form-data  # 문서 타입 지정
    parameters:
      - name: storeId
        in: path
        required: true
        schema:
          properties:
            storeId:
              type: integer
              example: 1
      - in: query
        name: directory
        type: string
      - in: formData
        name: image
        type: file
        description: 파일 업로드
      - in: formData
        name: userId
        type: integer
        description: 사용자 아이디
      - in: formData
        name: rate
        type: double
        description: 별점
      - in: formData
        name: content
        type: string
        description: 리뷰 내용

    responses:
  # 응답은 알아서~